version: '3.8'

services:
  whisper-transcript:
    build:
      context: .
      dockerfile: local.Dockerfile
    container_name: whisper-transcript
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 5000
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_USER: root
      DB_PASSWORD: root
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: rabbitmq
      RABBITMQ_PASSWORD: rabbitmq
      RABBITMQ_QUEUE_1: audio-transcription2
      SECRET_TOKEN: mrOiXV9o2cT9
      WHISPER_MODEL_NAME: tiny
      WHISPER_LANGUAGE: en
      WHISPER_VERBOSE: True
      WHISPER_FP16: False
    depends_on:
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ main port
      - "15672:15672"  # RabbitMQ management plugin port
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq

volumes:
  mongo-data:
    driver: local
  rabbitmq-data:
    driver: local
  rabbitmq-log:
    driver: local
